apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: web-app-bc
  name: web-app-bc
spec:
  output:
    to:
      kind: DockerImage
      name: quay.io/achevarria/cd:latest
    pushSecret:
      name: my-secret
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
